name: Bulid Electron App
on:
    pull_request:
        type: [opened, reopened, synchronize]
jobs:
    build-app:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: [14, 16, 18]
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v3
            - uses: node/checkout@v3
              with:
                  node-version: ${{matrix.node}}

            - run: npm install
            - run: node cli.js build --os ${{matrix.os}} --node ${{matrix.node}} > app-${{matrix.os}}-${{matrix.node}}.js

            - uses: actions/upload-artifact@v3
              with:
                  name: release-app
                  path: app-${{matrix.os}}-${{matrix.node}}.js
