name: Build Electron App

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    build-app:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                node: [14, 16, 18]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - run: npm ci
            - run: node cli.js build --os ${{ matrix.os }} --node ${{ matrix.node }} > app-${{ matrix.os }}-${{ matrix.node }}.js

            - uses: actions/upload-artifact@v4
              with:
                  name: released-app
                  path: app-${{ matrix.os }}-${{ matrix.node }}.js
