name: Coverage
on:
    push:
        branches: [main]
    pull_request:
        type: [opened, reopened, synchronize]
    workflow_dispatch:

jobs:
    Coverage-report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm install
            - uses: ArtiomTr/jest-coverage-report-action@v2
