name: hello world
on:
    push:
        branches: [main]
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "TODAY=$(Get-Date -Format "yyyy-MM-dd")" >> $GITHUB_ENV
            - run: echo hello world, today is $TODAY
