name: secrets
on:
    push:
        branches: [main]
    pull_request:
        types: [opened, reopened, synchronize]
    workflow_dispatch:

jobs:
    fetch-secrets:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
            - run: npm cache clean --force
            - run: npm install
            - run: ls -la node_modules/commander node_modules/randomstring
            - run: |
                  API_TOKEN=$(node cli.js rdstr)
                  echo "API_TOKEN=$API_TOKEN" >> $GITHUB_ENV
              env:
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            - run: echo "This is my token $API_TOKEN"
