name: secrets
on:
    push:
        branch: [main]
    pull_request:
        type: [opened, reopened, synchronize]
    workflow_dispatch:
jobs:
    fetch-secrets:
        runs-on: ubuntu-latest
        steps:
            - run: echo this is my secret ${{secrets.DB_PASSWORD}}
